-- Mini.nvim configurations are now handled in lua/plugins.lua
-- This file can be removed or used for additional mini.nvim customizations

-- Optional: Additional mini.animate setup if you want animations
-- require('mini.animate').setup({
--   cursor = {
--     enable = true,
--   },
--   scroll = {
--     enable = true,
--   },
--   resize = {
--     enable = true,
--   },
--   open = {
--     enable = true,
--   },
--   close = {
--     enable = true,
--   },
-- })

-- The mini.icons setup is now handled in the main plugin configuration